import { Player } from "./types/Player";

export const PLAYERS: Player[] = [
    {
      id: 1,
      name: 'LeBron James',
      position: ['SF', 'PF'],
      team: 'Los Angeles Lakers',
      league: 'NBA',
      age: 38,
      height: "6'9\"",
      weight: '250 lbs',
      salary: 44474988,
      contractYears: 2,
      ppg: 25,
      rebounds: 5,
      assists: 7,
      steals: 1.2,
      blocks: 0.8,
    },
    {
      id: 2,
      name: 'Stephen Curry',
      position: ['PG'],
      team: 'Golden State Warriors',
      league: 'NBA',
      age: 35,
      height: "6'3\"",
      weight: '185 lbs',
      salary: 51915615,
      contractYears: 4,
      ppg: 30,
      rebounds: 5,
      assists: 6,
      steals: 1.7,
      blocks: 0.4,
    },
    {
      id: 3,
      name: 'Kevin Durant',
      position: ['SF', 'PF'],
      team: 'Phoenix Suns',
      league: 'NBA',
      age: 34,
      height: "6'10\"",
      weight: '240 lbs',
      salary: 44119845,
      contractYears: 4,
      ppg: 27,
      rebounds: 7,
      assists: 5,
      steals: 1.1,
      blocks: 1.2,
    },
    {
      id: 4,
      name: 'Giannis Antetokounmpo',
      position: ['PF', 'C'],
      team: 'Milwaukee Bucks',
      league: 'NBA',
      age: 28,
      height: "6'11\"",
      weight: '242 lbs',
      salary: 45640084,
      contractYears: 4,
      ppg: 29,
      rebounds: 11,
      assists: 6,
      steals: 1.2,
      blocks: 1.4,
    },
    {
      id: 5,
      name: 'Luka Doncic',
      position: ['PG', 'SG'],
      team: 'Dallas Mavericks',
      league: 'NBA',
      age: 24,
      height: "6'7\"",
      weight: '230 lbs',
      salary: 37096500,
      contractYears: 5,
      ppg: 28,
      rebounds: 8,
      assists: 9,
      steals: 1.0,
      blocks: 0.6,
    },
  ];
  