import { Game } from "./types/Game";
import { Player } from "./types/Player";

export const PLAYERS: Player[] = [
  {
    id: 1,
    name: "LeBron James",
    position: ["SF", "PF"],
    team: "Los Angeles Lakers",
    league: "NBA",
    age: 38,
    height: "6'9\"",
    weight: "250 lbs",
    salary: 44474988,
    contractYears: 2,
    ppg: 25,
    rebounds: 5,
    assists: 7,
    steals: 1.2,
    blocks: 0.8,
    tag: 'high',
  },
  {
    id: 2,
    name: "Stephen Curry",
    position: ["PG"],
    team: "Golden State Warriors",
    league: "NBA",
    age: 35,
    height: "6'3\"",
    weight: "185 lbs",
    salary: 51915615,
    contractYears: 4,
    ppg: 30,
    rebounds: 5,
    assists: 6,
    steals: 1.7,
    blocks: 0.4,
    tag: 'medium'
  },
  {
    id: 3,
    name: "Kevin Durant",
    position: ["SF", "PF"],
    team: "Phoenix Suns",
    league: "NBA",
    age: 34,
    height: "6'10\"",
    weight: "240 lbs",
    salary: 44119845,
    contractYears: 4,
    ppg: 27,
    rebounds: 7,
    assists: 5,
    steals: 1.1,
    blocks: 1.2,
    tag: 'high',
  },
  {
    id: 4,
    name: "Giannis Antetokounmpo",
    position: ["PF", "C"],
    team: "Milwaukee Bucks",
    league: "NBA",
    age: 28,
    height: "6'11\"",
    weight: "242 lbs",
    salary: 45640084,
    contractYears: 4,
    ppg: 29,
    rebounds: 11,
    assists: 6,
    steals: 1.2,
    blocks: 1.4,
    tag: 'low',
  },
  {
    id: 5,
    name: "Luka Doncic",
    position: ["PG", "SG"],
    team: "Dallas Mavericks",
    league: "NBA",
    age: 24,
    height: "6'7\"",
    weight: "230 lbs",
    salary: 37096500,
    contractYears: 5,
    ppg: 28,
    rebounds: 8,
    assists: 9,
    steals: 1.0,
    blocks: 0.6,
    tag: 'medium'
  },
];

export const GAMES: Game[] = [
  {
    id: "1",
    date: "2024-10-11",
    time: "8:30 AM (CEST)",
    homeTeam: {
      name: "Adelaide 36ers",
      abbreviation: "ADE",
      logo: "",
      score: 89,
    },
    awayTeam: {
      name: "Sydney Kings",
      abbreviation: "SYD",
      logo: "",
      score: 79,
    },
  },
  {
    id: "2",
    date: "2024-10-12",
    time: "6:30 AM (CEST)",
    homeTeam: {
      name: "Illawarra Hawks",
      abbreviation: "ILL",
      logo: "",
      score: 109,
    },
    awayTeam: {
      name: "Tasmania JackJumpers",
      abbreviation: "TAS",
      logo: "",
      score: 76,
    },
  },
  {
    id: "3",
    date: "2024-10-12",
    time: "9:00 AM (CEST)",
    homeTeam: {
      name: "South East Melbourne Phoenix",
      abbreviation: "SOU",
      logo: "",
    },
    awayTeam: {
      name: "Brisbane Bullets",
      abbreviation: "BRI",
      logo: "",
    },
  },
  {
    id: "4",
    date: "2024-10-12",
    time: "9:00 AM (CEST)",
    homeTeam: {
      name: "South East Melbourne Phoenix",
      abbreviation: "SOU",
      logo: "",
    },
    awayTeam: {
      name: "Brisbane Bullets",
      abbreviation: "BRI",
      logo: "",
    },
  },
  {
    id: "5",
    date: "2024-10-12",
    time: "9:00 AM (CEST)",
    homeTeam: {
      name: "South East Melbourne Phoenix",
      abbreviation: "SOU",
      logo: "",
    },
    awayTeam: {
      name: "Brisbane Bullets",
      abbreviation: "BRI",
      logo: "",
    },
  },
  // {
  //   id: "6",
  //   date: "2024-10-12",
  //   time: "9:00 AM (CEST)",
  //   homeTeam: {
  //     name: "South East Melbourne Phoenix",
  //     abbreviation: "SOU",
  //     logo: "",
  //   },
  //   awayTeam: {
  //     name: "Brisbane Bullets",
  //     abbreviation: "BRI",
  //     logo: "",
  //   },
  // },
  // {
  //   id: "7",
  //   date: "2024-10-12",
  //   time: "9:00 AM (CEST)",
  //   homeTeam: {
  //     name: "South East Melbourne Phoenix",
  //     abbreviation: "SOU",
  //     logo: "",
  //   },
  //   awayTeam: {
  //     name: "Brisbane Bullets",
  //     abbreviation: "BRI",
  //     logo: "",
  //   },
  // },
];
